// Set here the color scheme and the marker(glyph) shape for the gene panel you are working
// with. These gene-specific shapes come into action at the deep zoom levels, when Leaflet.js
// takes over.
//
// There is switch for that called zoomSwitch, see line 39 of index.js together with the moveend
// callback, see lines 459 and 511 of dapi.js.
//
// Outside this deep zoom zone all genes have the same shape, a solid circle, see
// line 11, stage_markers_patched.js
//
// Note that leaflet doesnt get on very well with lots and lots of datapoints, if you notice
// some slowness on the viewer maybe changing the zoomSwitch from its default value of 7 to 8
// will probably help.
//
// Only the following shapes are supported:
//   star6
//   star5
//   diamond
//   square
//   triangleUp
//   triangleDown
//   triangleRight
//   triangleLeft
//   cross
//   plus
//   asterisk
//   circle
//   point
//
// These are designed in glyphPaths.js and introduced to the viewer from glyphs.js (no need to edit them
// unless you want to do an extra shape).


function glyphSettings()
{
    var out = [

        {gene: 'Col25a1', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Cplx2', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Gad1', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Lhx6', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Pnoc', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Rab3c', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Calb1', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Slc6a1', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Snca', color:'#006300', glyphName: 'asterisk'},
        {gene: 'Bcl11b', color:'#00CC00', glyphName: 'square'},
        {gene: 'Cdh13', color:'#00CC00', glyphName: 'square'},
        {gene: 'Gda', color:'#00CC00', glyphName: 'square'},
        {gene: 'Pde1a', color:'#00CC00', glyphName: 'square'},
        {gene: 'Prkca', color:'#00CC00', glyphName: 'square'},
        {gene: 'Rgs4', color:'#00CC00', glyphName: 'square'},
        {gene: 'Chrm2', color:'#00FF66', glyphName: 'cross'},
        {gene: 'Cox6a2', color:'#00FF66', glyphName: 'cross'},
        {gene: 'Pvalb', color:'#00FF66', glyphName: 'cross'},
        {gene: 'Tac1', color:'#00FF66', glyphName: 'cross'},
        {gene: 'Thsd7a', color:'#00FF66', glyphName: 'cross'},
        {gene: 'Chodl', color:'#387C02', glyphName: 'star5'},
        {gene: 'Cort', color:'#387C02', glyphName: 'star5'},
        {gene: 'Crhbp', color:'#387C02', glyphName: 'star5'},
        {gene: 'Grin3a', color:'#387C02', glyphName: 'star5'},
        {gene: 'Npy', color:'#387C02', glyphName: 'star5'},
        {gene: 'Reln', color:'#387C02', glyphName: 'star5'},
        {gene: 'Satb1', color:'#387C02', glyphName: 'star5'},
        {gene: 'Serpini1', color:'#387C02', glyphName: 'star5'},
        {gene: 'Sst', color:'#387C02', glyphName: 'star5'},
        {gene: 'Synpr', color:'#387C02', glyphName: 'star5'},
        {gene: 'Th', color:'#387C02', glyphName: 'star5'},
        {gene: 'Calb2', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Crh', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Htr3a', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Npy2r', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Penk', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Pthlh', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Tac2', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Vip', color:'#3F6826', glyphName: 'triangleDown'},
        {gene: 'Enpp2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Nrn1', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Pcp4', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Plcxd2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Rasgrf2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Wfs1', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Kcnk2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Neurod6', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Nr4a2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Gad2', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Igfbp4', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Myl1', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Npas1', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Rbp4', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Stmn1', color:'#4CBA16', glyphName: 'triangleLeft'},
        {gene: 'Cryab', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Gabrd', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Hapln1', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Id2', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Kit', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Lamp5', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Ndnf', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Nos1', color:'#54FF9E', glyphName: 'diamond'},
        {gene: 'Cck', color:'#70C670', glyphName: 'point'},
        {gene: 'Cnr1', color:'#70C670', glyphName: 'point'},
        {gene: 'Kctd12', color:'#70C670', glyphName: 'point'},
        {gene: 'Nov', color:'#70C670', glyphName: 'point'},
        {gene: 'Rgs10', color:'#70C670', glyphName: 'point'},
        {gene: 'Sema3c', color:'#70C670', glyphName: 'point'},
        {gene: 'Slc17a8', color:'#70C670', glyphName: 'point'},
        {gene: 'Sncg', color:'#70C670', glyphName: 'point'},
        {gene: 'Trp53i11', color:'#70C670', glyphName: 'point'},
        {gene: 'Yjefn3', color:'#70C670', glyphName: 'point'},
        {gene: 'Cadps2', color:'#7FFF00', glyphName: 'star6'},
        {gene: 'Cpne5', color:'#7FFF00', glyphName: 'star6'},
        {gene: 'Cxcl14', color:'#7FFF00', glyphName: 'star6'},
        {gene: 'Ntng1', color:'#7FFF00', glyphName: 'star6'},
        {gene: 'Rgs12', color:'#7FFF00', glyphName: 'star6'},
        {gene: 'Nrgn', color:'#99F999', glyphName: 'plus'},
        {gene: 'Slc17a7', color:'#99F999', glyphName: 'plus'},
        {gene: 'Sv2b', color:'#99F999', glyphName: 'plus'},
        {gene: 'Cplx3', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Crabp1', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Gng14', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Kcnd3', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Klrb1c', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Prlr', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Ttr', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd14', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd19', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd4', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd44', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd69', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Cd8a', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Chrna6', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Myl4', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Qrfpr', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Scg2', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Rgs2', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Bdnf', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Col23a1', color:'#87C67C', glyphName: 'triangleUp'},
        {gene: 'Gabrg1', color:'#96FFFF', glyphName: 'asterisk'},
        {gene: 'Mybpc1', color:'#96FFFF', glyphName: 'asterisk'},
        {gene: 'Nptx2', color:'#96FFFF', glyphName: 'asterisk'},
        {gene: 'Spp1', color:'#96FFFF', glyphName: 'asterisk'},
        {gene: 'Tnfaip6', color:'#96FFFF', glyphName: 'asterisk'},
        {gene: 'Ddit4l', color:'#99BFCC', glyphName: 'cirlce'},
        {gene: 'Gpr83', color:'#99BFCC', glyphName: 'cirlce'},
        {gene: 'Dkkl1', color:'#A3D3ED', glyphName: 'plus'},
        {gene: 'Hs3st2', color:'#A3D3ED', glyphName: 'plus'},
        {gene: 'Hsd11b1', color:'#A3D3ED', glyphName: 'plus'},
        {gene: 'Amigo2', color:'#0000FF', glyphName: 'square'},
        {gene: 'Cpne7', color:'#0000FF', glyphName: 'square'},
        {gene: 'Crym', color:'#0000FF', glyphName: 'square'},
        {gene: 'Fezf2', color:'#0000FF', glyphName: 'square'},
        {gene: 'Grik1', color:'#0000FF', glyphName: 'square'},
        {gene: 'Kcnip1', color:'#0000FF', glyphName: 'square'},
        {gene: 'Nxph1', color:'#0000FF', glyphName: 'square'},
        {gene: 'Tshz2', color:'#0000FF', glyphName: 'square'},
        {gene: 'Zbtb20', color:'#0000FF', glyphName: 'square'},
        {gene: 'Tnfaip8l3', color:'#0000FF', glyphName: 'square'},
        {gene: 'Parm1', color:'#00007F', glyphName: 'triangleLeft'},
        {gene: 'Serpine2', color:'#00007F', glyphName: 'triangleLeft'},
        {gene: 'Tafa1', color:'#00007F', glyphName: 'triangleLeft'},
        {gene: 'Akr1c18', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Arc', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Car4', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Cdh9', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Crispld2', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Gnb4', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Lypd6', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Plpp4', color:'#00C4BA', glyphName: 'diamond'},
        {gene: 'Mia', color:'#05EDFF', glyphName: 'triangleUp'},
        {gene: 'Prss23', color:'#05EDFF', glyphName: 'triangleUp'},
        {gene: 'Rprm', color:'#05EDFF', glyphName: 'triangleUp'},
        {gene: 'Scgn', color:'#05EDFF', glyphName: 'triangleUp'},
        {gene: 'Sema5a', color:'#05EDFF', glyphName: 'triangleUp'},
        {gene: 'Ccn2', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Cpne2', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Lgals1', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Nek7', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Qpct', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Tnmd', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Tpbg', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Zcchc12', color:'#2B4F82', glyphName: 'star6'},
        {gene: 'Chrm1', color:'#3A5ECC', glyphName: 'triangleRight'},
        {gene: 'Chrna3', color:'#3A5ECC', glyphName: 'triangleRight'},
        {gene: 'Chrna4', color:'#3A5ECC', glyphName: 'triangleRight'},
        {gene: 'Chrnb2', color:'#3A5ECC', glyphName: 'triangleRight'},
        {gene: 'Abi3bp', color:'#E2CE56', glyphName: 'cirlce'},
        {gene: 'Ctxn3', color:'#E2CE56', glyphName: 'cirlce'},
        {gene: 'Kcnip2', color:'#E2CE56', glyphName: 'cirlce'},
        {gene: 'Meis2', color:'#E2CE56', glyphName: 'cirlce'},
        {gene: 'Pcp4l1', color:'#E2CE56', glyphName: 'cirlce'},
        {gene: 'Cbln2', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Npnt', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Sln', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Tcf7l2', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Tnnt1', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Tpd52l1', color:'#EDED00', glyphName: 'star6'},
        {gene: 'Ddc', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Dlk1', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Maob', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Slc18a2', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Slc6a4', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Slc6a5', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Sv2c', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Syt2', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Tph2', color:'#F4F775', glyphName: 'plus'},
        {gene: 'Acly', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Aldh1a1', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Cartpt', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Cbln1', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Ctxn2', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Enc1', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Gchfr', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Gpx3', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Ngb', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Nnat', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Ret', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Rln3', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Slc10a4', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Slc5a7', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Ucn', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Slc6a3', color:'#EDC900', glyphName: 'cross'},
        {gene: 'Adcyap1', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Afp', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Bdnf', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'C1ql1', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Cd24a', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Dbh', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Etv1', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Foxp2', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Gpr88', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Hoxb8', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Igfbp5', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Irs4', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Npff', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Peg10', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Pgr15l', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Phox2b', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Pou4f1', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Prph', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Rims4', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Slc17a6', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Slc6a2', color:'#F9ED5B', glyphName: 'triangleRight'},
        {gene: 'Adora2a', color:'#FFFF7C', glyphName: 'triangleLeft'},
        {gene: 'Agrp', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Avp', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Ecel1', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Gal', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Gnrh1', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Gpr101', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Hcrt', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Ngfr', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Nts', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Otp', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Oxt', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Pdyn', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Pmch', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Scg2', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Trh', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'Ucn3', color:'#FFFF00', glyphName: 'asterisk'},
        {gene: 'C1ql3', color:'#FFED8C', glyphName: 'square'},
        {gene: 'Lypd1', color:'#FFED8C', glyphName: 'square'},
        {gene: 'Necab2', color:'#FFD600', glyphName: 'point'},
        {gene: 'Nwd2', color:'#FFD600', glyphName: 'point'},
        {gene: 'Prkcd', color:'#FFD600', glyphName: 'point'},
        {gene: 'Ramp3', color:'#FFD600', glyphName: 'point'},
        {gene: 'Gng13', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Lgi2', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Nptx1', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Pcp2', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Slc1a6', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Slc32a1', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Zic1', color:'#F4F775', glyphName: 'triangleDown'},
        {gene: 'Ifitm3', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'Spp1', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'Ctsl', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'B2m', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'Ctsb', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'Cd63', color:'#C61484', glyphName: 'asterisk'},
        {gene: 'C1qa', color:'#CC6889', glyphName: 'cross'},
        {gene: 'Hexb', color:'#CC6889', glyphName: 'cross'},
        {gene: 'P2ry12', color:'#CC6889', glyphName: 'cross'},
        {gene: 'Tmem119', color:'#CC6889', glyphName: 'cross'},
        {gene: 'Trem2', color:'#CC6889', glyphName: 'cross'},
        {gene: 'C1qb', color:'#DBA3CC', glyphName: 'star5'},
        {gene: 'Ccl4', color:'#DBA3CC', glyphName: 'star5'},
        {gene: 'Ctsd', color:'#DBA3CC', glyphName: 'star5'},
        {gene: 'Ctss', color:'#DBA3CC', glyphName: 'star5'},
        {gene: 'Cx3cr1', color:'#EDA8B7', glyphName: 'triangleDown'},
        {gene: 'Itgam', color:'#EDA8B7', glyphName: 'triangleDown'},
        {gene: 'Tyrobp', color:'#EDC1BF', glyphName: 'point'},
        {gene: 'Fcer1g', color:'#EDC1BF', glyphName: 'point'},
        {gene: 'C1qc', color:'#EDC1BF', glyphName: 'point'},
        {gene: 'Agt', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Apoe', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Aqp4', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Fam107a', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Fbln5', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Gfap', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Gja1', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Glul', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Myoc', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Sfrp1', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Slc1a3', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Slc6a11', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Sparc', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Vim', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Aldoc', color:'#BF5EFF', glyphName: 'asterisk'},
        {gene: 'Fn1', color:'#B71123', glyphName: 'cirlce'},
        {gene: 'Igfbp6', color:'#B71123', glyphName: 'cirlce'},
        {gene: 'Mgp', color:'#B71123', glyphName: 'cirlce'},
        {gene: 'Igfbp2', color:'#B71123', glyphName: 'cirlce'},
        {gene: 'Ptgds', color:'#B71123', glyphName: 'cirlce'},
        {gene: 'Epas1', color:'#FF0000', glyphName: 'plus'},
        {gene: 'Flt1', color:'#FF0000', glyphName: 'plus'},
        {gene: 'Igf2', color:'#FF0000', glyphName: 'plus'},
        {gene: 'Rgs5', color:'#FF0000', glyphName: 'plus'},
        {gene: 'Bsg', color:'#CC5454', glyphName: 'square'},
        {gene: 'Itm2a', color:'#CC5454', glyphName: 'square'},
        {gene: 'Pltp', color:'#CC5454', glyphName: 'square'},
        {gene: 'Myl9', color:'#FF3F3F', glyphName: 'star5'},
        {gene: 'Tagln', color:'#FF3F3F', glyphName: 'star5'},
        {gene: 'Car2', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'Apod', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'Mog', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'S100b', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'Trf', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'Plp1', color:'#FF7216', glyphName: 'asterisk'},
        {gene: 'Cd81', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Mag', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Mobp', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Olig1', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Opalin', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Tspan2', color:'#FF9954', glyphName: 'triangleUp'},
        {gene: 'Gng12', color:'#FFAF0F', glyphName: 'point'},
        {gene: 'Marcks', color:'#FFAF0F', glyphName: 'point'},
        {gene: 'Sirt2', color:'#FFAF0F', glyphName: 'point'},
        {gene: 'Rras2', color:'#FFAF0F', glyphName: 'point'},
        {gene: 'Qk', color:'#FFAF0F', glyphName: 'point'},
        {gene: 'Gpr17', color:'#FFCC99', glyphName: 'star6'},
        {gene: 'Fabp7', color:'#FFCC99', glyphName: 'star6'},
        {gene: 'Cldn5', color:'#FFFFFF', glyphName: 'asterisk'},
        {gene: 'Higd1b', color:'#FFFFFF', glyphName: 'asterisk'},
        {gene: 'Igfbp7', color:'#FFFFFF', glyphName: 'asterisk'},
        {gene: 'Pglyrp1', color:'#FFFFFF', glyphName: 'asterisk'},
        {gene: 'Vtn', color:'#FFFFFF', glyphName: 'asterisk'},
        {gene: 'Cdhr1', color:'#FCF4E5', glyphName: 'triangleUp'},
        {gene: 'Doc2g', color:'#FCF4E5', glyphName: 'triangleUp'},
        {gene: 'Gnb3', color:'#FCF4E5', glyphName: 'triangleUp'},
        {gene: 'Sag', color:'#FCF4E5', glyphName: 'triangleUp'},
        {gene: 'Dbi', color:'#EFFFEF', glyphName: 'point'},
        {gene: 'Foxj1', color:'#EFFFEF', glyphName: 'point'},
        {gene: 'Rarres2', color:'#EFFFEF', glyphName: 'point'},
        {gene: 'Riiad1', color:'#EFFFEF', glyphName: 'point'},
        {gene: 'Ecrg4', color:'#E5E8F9', glyphName: 'star5'},
        {gene: 'Sostdc1', color:'#E5E8F9', glyphName: 'star5'},
        {gene: 'Ttr', color:'#E5E8F9', glyphName: 'star5'},
        {gene: 'Dcn', color:'#E5E8F9', glyphName: 'star5'},
        {gene: 'Fos', color:'#E0FFFF', glyphName: 'square'},
        {gene: 'Fosb', color:'#E0FFFF', glyphName: 'square'},
        {gene: 'Junb', color:'#E0FFFF', glyphName: 'square'},




        // Do not remove this. If a gene is missing from the settings above, use these as default
        {gene: 'Generic',       color: '#0000FF',   glyphName: 'circle'},

        ];

    return out
}
