function classColorsCodes_tasic() {
    return [
        {'className': 'Astro Aqp4', 'IdentifiedType': 'Astro Aqp4', 'color': '#0000FF'},
        {'className': 'Endo Ctla2a', 'IdentifiedType': 'Endo Ctla2a', 'color': '#00FF00'},
        {'className': 'L2/3 IT VISp Adamts2', 'IdentifiedType': 'L2/3 IT VISp Adamts2', 'color': '#FF0000'},
        {'className': 'L2/3 IT VISp Agmat', 'IdentifiedType': 'L2/3 IT VISp Agmat', 'color': '#409FBF'},
        {'className': 'L2/3 IT VISp Rrad', 'IdentifiedType': 'L2/3 IT VISp Rrad', 'color': '#DF209F'},
        {'className': 'L4 IT VISp Rspo1', 'IdentifiedType': 'L4 IT VISp Rspo1', 'color': '#DFBF40'},
        {'className': 'L5 IT VISp Batf3', 'IdentifiedType': 'L5 IT VISp Batf3', 'color': '#5AC387'},
        {'className': 'L5 IT VISp Col27a1', 'IdentifiedType': 'L5 IT VISp Col27a1', 'color': '#00FFBF'},
        {'className': 'L5 IT VISp Col6a1 Fezf2', 'IdentifiedType': 'L5 IT VISp Col6a1 Fezf2', 'color': '#0060DF'},
        {'className': 'L5 IT VISp Hsd11b1 Endou', 'IdentifiedType': 'L5 IT VISp Hsd11b1 Endou', 'color': '#802020'},
        {'className': 'L5 IT VISp Whrn Tox2', 'IdentifiedType': 'L5 IT VISp Whrn Tox2', 'color': '#FFBFBF'},
        {'className': 'L5 NP VISp Trhr Cpne7', 'IdentifiedType': 'L5 NP VISp Trhr Cpne7', 'color': '#409F00'},
        {'className': 'L5 NP VISp Trhr Met', 'IdentifiedType': 'L5 NP VISp Trhr Met', 'color': '#DF20FF'},
        {'className': 'L5 PT VISp C1ql2 Cdh13', 'IdentifiedType': 'L5 PT VISp C1ql2 Cdh13', 'color': '#602060'},
        {'className': 'L5 PT VISp C1ql2 Ptgfr', 'IdentifiedType': 'L5 PT VISp C1ql2 Ptgfr', 'color': '#DF9FFF'},
        {'className': 'L5 PT VISp Chrna6', 'IdentifiedType': 'L5 PT VISp Chrna6', 'color': '#FF0060'},
        {'className': 'L5 PT VISp Krt80', 'IdentifiedType': 'L5 PT VISp Krt80', 'color': '#BFDF9F'},
        {'className': 'L6 CT VISp Ctxn3 Brinp3', 'IdentifiedType': 'L6 CT VISp Ctxn3 Brinp3', 'color': '#BF6000'},
        {'className': 'L6 CT VISp Ctxn3 Sla', 'IdentifiedType': 'L6 CT VISp Ctxn3 Sla', 'color': '#BFFF20'},
        {'className': 'L6 CT VISp Gpr139', 'IdentifiedType': 'L6 CT VISp Gpr139', 'color': '#009F80'},
        {'className': 'L6 CT VISp Krt80 Sla', 'IdentifiedType': 'L6 CT VISp Krt80 Sla', 'color': '#80009F'},
        {'className': 'L6 CT VISp Nxph2 Wls', 'IdentifiedType': 'L6 CT VISp Nxph2 Wls', 'color': '#004060'},
        {'className': 'L6 IT VISp Car3', 'IdentifiedType': 'L6 IT VISp Car3', 'color': '#60FFFF'},
        {'className': 'L6 IT VISp Col18a1', 'IdentifiedType': 'L6 IT VISp Col18a1', 'color': '#009FFF'},
        {'className': 'L6 IT VISp Col23a1 Adamts2', 'IdentifiedType': 'L6 IT VISp Col23a1 Adamts2', 'color': '#808040'},
        {'className': 'L6 IT VISp Penk Col27a1', 'IdentifiedType': 'L6 IT VISp Penk Col27a1', 'color': '#9FFF80'},
        {'className': 'L6 IT VISp Penk Fst', 'IdentifiedType': 'L6 IT VISp Penk Fst', 'color': '#BF6080'},
        {'className': 'L6b P2ry12', 'IdentifiedType': 'L6b P2ry12', 'color': '#0020BF'},
        {'className': 'L6b VISp Col8a1 Rprm', 'IdentifiedType': 'L6b VISp Col8a1 Rprm', 'color': '#DF9F60'},
        {'className': 'L6b VISp Col8a1 Rxfp1', 'IdentifiedType': 'L6b VISp Col8a1 Rxfp1', 'color': '#604020'},
        {'className': 'L6b VISp Crh', 'IdentifiedType': 'L6b VISp Crh', 'color': '#BFDFFF'},
        {'className': 'L6b VISp Mup5', 'IdentifiedType': 'L6b VISp Mup5', 'color': '#60609F'},
        {'className': 'Lamp5 Fam19a1 Pax6', 'IdentifiedType': 'Lamp5 Fam19a1 Pax6', 'color': '#FF9F00'},
        {'className': 'Lamp5 Fam19a1 Tmem182', 'IdentifiedType': 'Lamp5 Fam19a1 Tmem182', 'color': '#9F60FF'},
        {'className': 'Lamp5 Krt73', 'IdentifiedType': 'Lamp5 Krt73', 'color': '#BF2020'},
        {'className': 'Lamp5 Lhx6', 'IdentifiedType': 'Lamp5 Lhx6', 'color': '#FF8060'},
        {'className': 'Lamp5 Lsp1', 'IdentifiedType': 'Lamp5 Lsp1', 'color': '#9FBF00'},
        {'className': 'Lamp5 Ntn1 Npy2r', 'IdentifiedType': 'Lamp5 Ntn1 Npy2r', 'color': '#006060'},
        {'className': 'Lamp5 Plch2 Dock5', 'IdentifiedType': 'Lamp5 Plch2 Dock5', 'color': '#BF0060'},
        {'className': 'Meis2 Adamts19', 'IdentifiedType': 'Meis2 Adamts19', 'color': '#00BF60'},
        {'className': 'Microglia Siglech', 'IdentifiedType': 'Microglia Siglech', 'color': '#00FF80'},
        {'className': 'Oligo Serpinb1a', 'IdentifiedType': 'Oligo Serpinb1a', 'color': '#608000'},
        {'className': 'Peri Kcnj8', 'IdentifiedType': 'Peri Kcnj8', 'color': '#FFDF00'},

        // Default classes (always included)
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},
        {className: 'Generic', IdentifiedType: 'Generic', color: '#C0C0C0'},
        {className: 'Other', IdentifiedType: 'Other', color: '#C0C0C0'}
    ];
}