/**
 * Zeisel Dataset Color Scheme
 */

function classColorsCodes_zeisel() {
    return [
        {'className': 'ABC', 'IdentifiedType': 'ABC', 'color': '#B71123'},
        {'className': 'ACTE1', 'IdentifiedType': 'ACTE1', 'color': '#BF5EFF'},
        {'className': 'ACTE2', 'IdentifiedType': 'ACTE2', 'color': '#BF5EFF'},
        {'className': 'DGGRC1', 'IdentifiedType': 'DGGRC1', 'color': '#004f63'},
        {'className': 'DGGRC2', 'IdentifiedType': 'DGGRC2', 'color': '#16baa4'},
        {'className': 'DGNBL1', 'IdentifiedType': 'DGNBL1', 'color': '#16baa4'},
        {'className': 'DGNBL2', 'IdentifiedType': 'DGNBL2', 'color': '#004f63'},
        {'className': 'EPEN', 'IdentifiedType': 'EPEN', 'color': '#EFFFEF'},
        {'className': 'MFOL1', 'IdentifiedType': 'MFOL1', 'color': '#FF7216'},
        {'className': 'MFOL2', 'IdentifiedType': 'MFOL2', 'color': '#FF7216'},
        {'className': 'MGL1', 'IdentifiedType': 'MGL1', 'color': '#CC6889'},
        {'className': 'MGL2', 'IdentifiedType': 'MGL2', 'color': '#CC6889'},
        {'className': 'MGL3', 'IdentifiedType': 'MGL3', 'color': '#CC6889'},
        {'className': 'MOL1', 'IdentifiedType': 'MOL1', 'color': '#FF7216'},
        {'className': 'MOL2', 'IdentifiedType': 'MOL2', 'color': '#FF7216'},
        {'className': 'MOL3', 'IdentifiedType': 'MOL3', 'color': '#FF7216'},
        {'className': 'OPC', 'IdentifiedType': 'OPC', 'color': '#EFFFEF'},
        {'className': 'PER1', 'IdentifiedType': 'PER1', 'color': '#CC5454'},
        {'className': 'PER2', 'IdentifiedType': 'PER2', 'color': '#CC5454'},
        {'className': 'PER3', 'IdentifiedType': 'PER3', 'color': '#FFFFFF'},
        {'className': 'TEGLU1', 'IdentifiedType': 'TEGLU1', 'color': '#4CBA16'},
        {'className': 'TEGLU10', 'IdentifiedType': 'TEGLU10', 'color': '#4CBA16'},
        {'className': 'TEGLU11', 'IdentifiedType': 'TEGLU11', 'color': '#70C670'},
        {'className': 'TEGLU12', 'IdentifiedType': 'TEGLU12', 'color': '#70C670'},
        {'className': 'TEGLU13', 'IdentifiedType': 'TEGLU13', 'color': '#70C670'},
        {'className': 'TEGLU14', 'IdentifiedType': 'TEGLU14', 'color': '#99F999'},
        {'className': 'TEGLU2', 'IdentifiedType': 'TEGLU2', 'color': '#4CBA16'},
        {'className': 'TEGLU20', 'IdentifiedType': 'TEGLU20', 'color': '#70C670'},
        {'className': 'TEGLU21', 'IdentifiedType': 'TEGLU21', 'color': '#4CBA16'},
        {'className': 'TEGLU23', 'IdentifiedType': 'TEGLU23', 'color': '#006300'},
        {'className': 'TEGLU24', 'IdentifiedType': 'TEGLU24', 'color': '#99F999'},
        {'className': 'TEGLU3', 'IdentifiedType': 'TEGLU3', 'color': '#4CBA16'},
        {'className': 'TEGLU4', 'IdentifiedType': 'TEGLU4', 'color': '#4CBA16'},
        {'className': 'TEGLU6', 'IdentifiedType': 'TEGLU6', 'color': '#70C670'},
        {'className': 'TEGLU7', 'IdentifiedType': 'TEGLU7', 'color': '#99F999'},
        {'className': 'TEGLU8', 'IdentifiedType': 'TEGLU8', 'color': '#99F999'},
        {'className': 'TEGLU9', 'IdentifiedType': 'TEGLU9', 'color': '#4CBA16'},
        {'className': 'TEINH10', 'IdentifiedType': 'TEINH10', 'color': '#70C670'},
        {'className': 'TEINH11', 'IdentifiedType': 'TEINH11', 'color': '#70C670'},
        {'className': 'TEINH12', 'IdentifiedType': 'TEINH12', 'color': '#70C670'},
        {'className': 'TEINH13', 'IdentifiedType': 'TEINH13', 'color': '#70C670'},
        {'className': 'TEINH14', 'IdentifiedType': 'TEINH14', 'color': '#7FFF00'},
        {'className': 'TEINH15', 'IdentifiedType': 'TEINH15', 'color': '#387C02'},
        {'className': 'TEINH16', 'IdentifiedType': 'TEINH16', 'color': '#387C02'},
        {'className': 'TEINH17', 'IdentifiedType': 'TEINH17', 'color': '#006300'},
        {'className': 'TEINH18', 'IdentifiedType': 'TEINH18', 'color': '#00FF66'},
        {'className': 'TEINH19', 'IdentifiedType': 'TEINH19', 'color': '#387C02'},
        {'className': 'TEINH20', 'IdentifiedType': 'TEINH20', 'color': '#4CBA16'},
        {'className': 'TEINH21', 'IdentifiedType': 'TEINH21', 'color': '#387C02'},
        {'className': 'TEINH4', 'IdentifiedType': 'TEINH4', 'color': '#3F6826'},
        {'className': 'TEINH5', 'IdentifiedType': 'TEINH5', 'color': '#3F6826'},
        {'className': 'TEINH6', 'IdentifiedType': 'TEINH6', 'color': '#7FFF00'},
        {'className': 'TEINH7', 'IdentifiedType': 'TEINH7', 'color': '#3F6826'},
        {'className': 'TEINH8', 'IdentifiedType': 'TEINH8', 'color': '#3F6826'},
        {'className': 'TEINH9', 'IdentifiedType': 'TEINH9', 'color': '#70C670'},
        {'className': 'VECA', 'IdentifiedType': 'VECA', 'color': '#FF0000'},
        {'className': 'VECC', 'IdentifiedType': 'VECC', 'color': '#CC5454'},
        {'className': 'VECV', 'IdentifiedType': 'VECV', 'color': '#CC5454'},
        {'className': 'VLMC1', 'IdentifiedType': 'VLMC1', 'color': '#FF7216'},
        {'className': 'VLMC2', 'IdentifiedType': 'VLMC2', 'color': '#B71123'},
        {'className': 'VSMCA', 'IdentifiedType': 'VSMCA', 'color': '#FF3F3F'},

        // Default classes (always included)
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},
        {className: 'Generic', IdentifiedType: 'Generic', color: '#C0C0C0'},
        {className: 'Other', IdentifiedType: 'Other', color: '#C0C0C0'}
    ];
}